/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zouhaib mahamoud
 */
public class ecranacceuille extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ecranacceuille.class.getName());

    /**
     * Creates new form ecranacceuille
     */
    public ecranacceuille() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        levelgame = new javax.swing.JLabel();
        Jouer = new javax.swing.JButton();
        combo_difficulte = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bienvenue dans le jeu de Cadena");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 6, -1, -1));

        levelgame.setText("Choisir le niveau de jeu:");
        getContentPane().add(levelgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 81, -1, -1));

        Jouer.setText("Jouer");
        Jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JouerActionPerformed(evt);
            }
        });
        getContentPane().add(Jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 163, -1, -1));

        combo_difficulte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facile", "Normal", "Difficile", "Entraînement" }));
        combo_difficulte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_difficulteActionPerformed(evt);
            }
        });
        getContentPane().add(combo_difficulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 78, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_difficulteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_difficulteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_difficulteActionPerformed

    private void JouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JouerActionPerformed
        String niveau = combo_difficulte.getSelectedItem().toString();
        int tentativesMax;

        if (niveau.equals("Facile")) {
            tentativesMax = 8;
        } 
        else if (niveau.equals("Normal")) {
            tentativesMax = 6;
        }
        else if (niveau.equals("Difficile")) {
            tentativesMax = 4;
        }
        else {
          tentativesMax = 999; // Entraînement = quasi illimité
        }

        new Jeu1(tentativesMax).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new ecranacceuille().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jouer;
    private javax.swing.JComboBox<String> combo_difficulte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel levelgame;
    // End of variables declaration//GEN-END:variables
}
