/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zouhaib mahamoud
 */
public class Jeu1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jeu1.class.getName());
    private tete_du_jeu_zouhaib jeu;
    /**
     * Creates new form Jeu1
     */
    public Jeu1() {
        initComponents();
        jeu = new tete_du_jeu_zouhaib();   // création de la logique de jeu
        rafraichirAffichageChiffres();     // on affiche 0 0 0 0
        texte_tentatives.setText(" 0 sur " + jeu.getNbTentativesMax());
        texte_score.setText("Tentatives");
    }
    private void rafraichirAffichageChiffres() {
        texte_chiffre_0.setText(" " + jeu.getProposition(0));
        texte_chiffre_1.setText(" " + jeu.getProposition(1));
        texte_chiffre_2.setText(" " + jeu.getProposition(2));
        texte_chiffre_3.setText(" " + jeu.getProposition(3));
    }
    private void desactiverBoutons() {
        up_chiffre_1.setEnabled(false);
        up_chiffre_2.setEnabled(false);
        up_chiffre_3.setEnabled(false);
        up_chiffre_4.setEnabled(false);

        down_chiffre_1.setEnabled(false);
        down_chiffre_2.setEnabled(false);
        down_chiffre_3.setEnabled(false);
        down_chiffre_4.setEnabled(false);

        bouton_tester.setEnabled(false);
    }

    private void activerBoutons() {
        up_chiffre_1.setEnabled(true);
        up_chiffre_2.setEnabled(true);
        up_chiffre_3.setEnabled(true);
        up_chiffre_4.setEnabled(true);

        down_chiffre_1.setEnabled(true);
        down_chiffre_2.setEnabled(true);
        down_chiffre_3.setEnabled(true);
        down_chiffre_4.setEnabled(true);

        bouton_tester.setEnabled(true);
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_score = new javax.swing.JLabel();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("trouver le bon code en moins de 5 tentatives  ");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 6, 450, -1));

        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exact:      ");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 237, -1, -1));

        texte_lbl_nb_chiffres_haut.setText("Nomre de chiffres trop hauts:");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, -1, -1));

        texte_lbl_nb_chiffres_bas.setText("Nomre de chiffres trop bas:");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 284, -1, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 67, -1));

            texte_nb_chiffres_exacts.setText("0");
            getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 237, -1, -1));

            texte_nb_chiffres_haut.setText("0");
            getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 259, -1, -1));

            texte_nb_chiffres_bas.setText("0");
            getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 284, -1, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 22, 66, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 22, 69, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 22, -1, -1));

                        texte_score.setText("tentatives");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 178, -1, -1));

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_0.setText("  0");
                        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, 67, 68));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_1.setText("  0");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 63, 66, 68));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_2.setText("  0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 63, 69, 68));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 67, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 164, 66, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 164, 69, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 164, -1, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_3.setText("  0");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 63, 72, 68));

                        texte_tentatives.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                        texte_tentatives.setText(" 0 sur 5");
                        texte_tentatives.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 206, 64, 50));

                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 281, -1, -1));

                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        jeu.incrementerChiffre(0);
        rafraichirAffichageChiffres();
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        jeu.incrementerChiffre(1);
        rafraichirAffichageChiffres();
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        jeu.incrementerChiffre(2);
        rafraichirAffichageChiffres();   
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        jeu.incrementerChiffre(3);
        rafraichirAffichageChiffres();
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        jeu.decrementerChiffre(1);
        rafraichirAffichageChiffres();
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        jeu.decrementerChiffre(2);
        rafraichirAffichageChiffres();
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        jeu.decrementerChiffre(3);
        rafraichirAffichageChiffres();
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        jeu.nouvellePartie();
        rafraichirAffichageChiffres();

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_nb_chiffres_bas.setText("0");

        texte_tentatives.setText(" 0 sur " + jeu.getNbTentativesMax());
        texte_score.setText("Tentatives");

        activerBoutons();
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        tete_du_jeu_zouhaib.Resultat res = jeu.tester();

        texte_nb_chiffres_exacts.setText(String.valueOf(res.getNbExact()));
        texte_nb_chiffres_haut.setText(String.valueOf(res.getNbTropHaut()));
        texte_nb_chiffres_bas.setText(String.valueOf(res.getNbTropBas()));

        texte_tentatives.setText(" " + jeu.getNbTentatives() + " sur " + jeu.getNbTentativesMax());

        if (jeu.estGagne()) {
            texte_score.setText("Bravo, vous avez gagné !");
            desactiverBoutons();
        } else if (jeu.partieTerminee()) {
            texte_score.setText("Dommage, partie terminée.");
            desactiverBoutons();
        } else {
            texte_score.setText("Tentatives");
        }
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        jeu.decrementerChiffre(0);
        rafraichirAffichageChiffres();
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Jeu1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
