/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.Timer;
/**
 *
 * @author zouhaib mahamoud
 */
public class Jeu1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jeu1.class.getName());
    private tete_du_jeu_zouhaib jeu;
    /**
     * Creates new form Jeu1
     */
    private Timer timerClignote;
    private boolean etatVisible = true;
    
    private int parties = 0;
    private int victoires = 0;
    private java.util.HashSet<String> combinaisonsTestees = new java.util.HashSet<>();
    private boolean chiffreModifie = false;
    public Jeu1(int tentativesMax) {
        initComponents();
        jeu = new tete_du_jeu_zouhaib(tentativesMax);
        rafraichirAffichageChiffres();
        texte_tentatives.setText(" 0 sur " + jeu.getNbTentativesMax());
        texte_score.setText("Tentatives");

        texte_intro.setText("Le jeu consiste à trouver le code du cadenas en " 
            + tentativesMax + " tentatives.");
        bouton_tester.setEnabled(false);
        chiffreModifie = false;
        if (tentativesMax >= 100) {
        texte_intro.setText(
            "Mode entraînement : trouvez le code du cadenas sans limite de tentatives."
        );
    } else {
        texte_intro.setText(
            "Le jeu consiste à trouver le code du cadenas en " 
            + tentativesMax + " tentatives."
    );
}
    
    }
    private void rafraichirAffichageChiffres() {
        texte_chiffre_0.setText(" " + jeu.getProposition(0));
        texte_chiffre_1.setText(" " + jeu.getProposition(1));
        texte_chiffre_2.setText(" " + jeu.getProposition(2));
        texte_chiffre_3.setText(" " + jeu.getProposition(3));
    }
    private void desactiverBoutons() {
        up_chiffre_1.setEnabled(false);
        up_chiffre_2.setEnabled(false);
        up_chiffre_3.setEnabled(false);
        up_chiffre_4.setEnabled(false);

        down_chiffre_1.setEnabled(false);
        down_chiffre_2.setEnabled(false);
        down_chiffre_3.setEnabled(false);
        down_chiffre_4.setEnabled(false);

        bouton_tester.setEnabled(false);
    }

    private void activerBoutons() {
        up_chiffre_1.setEnabled(true);
        up_chiffre_2.setEnabled(true);
        up_chiffre_3.setEnabled(true);
        up_chiffre_4.setEnabled(true);

        down_chiffre_1.setEnabled(true);
        down_chiffre_2.setEnabled(true);
        down_chiffre_3.setEnabled(true);
        down_chiffre_4.setEnabled(true);

        bouton_tester.setEnabled(true);
    }
    private String propositionToString() {
    return jeu.getProposition(0) + " " + jeu.getProposition(1) + " "
         + jeu.getProposition(2) + " " + jeu.getProposition(3);
    }
    private void lancerClignotement() {
    if (timerClignote != null) timerClignote.stop();

    timerClignote = new Timer(300, e -> {
        etatVisible = !etatVisible;
        texte_score.setVisible(etatVisible);
    });
    timerClignote.start();
    }
    private void majStats() {
    lbl_stats.setText("Parties: " + parties + " | Victoires: " + victoires);
    }
    private String combinaisonActuelle() {
    return jeu.getProposition(0) + "-"
         + jeu.getProposition(1) + "-"
         + jeu.getProposition(2) + "-"
         + jeu.getProposition(3);
    }
   

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_score = new javax.swing.JLabel();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        bouton_aide = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        zone_historique = new javax.swing.JTextArea();
        lbl_stats = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Le jeu consiste à trouver le code du cadenas en");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 450, -1));

        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exact:      ");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 237, -1, -1));

        texte_lbl_nb_chiffres_haut.setText("Nomre de chiffres trop hauts:");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, -1, -1));

        texte_lbl_nb_chiffres_bas.setText("Nomre de chiffres trop bas:");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 284, -1, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 67, -1));

            texte_nb_chiffres_exacts.setText("0");
            getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 237, -1, -1));

            texte_nb_chiffres_haut.setText("0");
            getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 259, -1, -1));

            texte_nb_chiffres_bas.setText("0");
            getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 284, -1, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 22, 66, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 22, 69, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 22, 70, -1));

                        texte_score.setText("tentatives");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 178, -1, -1));

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_0.setText("  0");
                        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, 67, 68));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_1.setText("  0");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 63, 66, 68));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_2.setText("  0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 63, 69, 68));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, 67, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 164, 66, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 164, 69, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 164, 70, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        texte_chiffre_3.setText("  0");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 63, 72, 68));

                        texte_tentatives.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                        texte_tentatives.setText(" 0 sur 5");
                        texte_tentatives.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 206, 64, 50));

                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 281, -1, -1));

                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

                        bouton_aide.setText("Aide  ");
                        bouton_aide.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_aideActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_aide, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

                        zone_historique.setColumns(20);
                        zone_historique.setRows(5);
                        jScrollPane1.setViewportView(zone_historique);

                        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 360, 90));

                        lbl_stats.setText("Parties: 0 | Victoires: 0");
                        getContentPane().add(lbl_stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        jeu.incrementerChiffre(0);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        jeu.incrementerChiffre(1);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        jeu.incrementerChiffre(2);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        jeu.incrementerChiffre(3);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        jeu.decrementerChiffre(1);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        jeu.decrementerChiffre(2);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        jeu.decrementerChiffre(3);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        jeu.nouvellePartie();
        rafraichirAffichageChiffres();

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_nb_chiffres_bas.setText("0");

        texte_tentatives.setText(" 0 sur " + jeu.getNbTentativesMax());
        texte_score.setText("Tentatives");
        zone_historique.setText("");
        if (timerClignote != null) timerClignote.stop();
        texte_score.setVisible(true);
        etatVisible = true;
        combinaisonsTestees.clear();
        bouton_tester.setEnabled(false);
        chiffreModifie = false;
        
        
        activerBoutons();
        
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        tete_du_jeu_zouhaib.Resultat res = jeu.tester();

        texte_nb_chiffres_exacts.setText(String.valueOf(res.getNbExact()));
        texte_nb_chiffres_haut.setText(String.valueOf(res.getNbTropHaut()));
        texte_nb_chiffres_bas.setText(String.valueOf(res.getNbTropBas()));

        if (jeu.getNbTentativesMax() >= 100) {
        texte_tentatives.setText(" Tentatives : " + jeu.getNbTentatives());
        }
        else {
            texte_tentatives.setText(" " + jeu.getNbTentatives() + " sur " + jeu.getNbTentativesMax());
        }

       // SI GAGNÉ
        if (jeu.estGagne()) {
            int[] code = jeu.getCodeSecret();
            texte_score.setText("Bravo ! Code secret : " 
                + code[0] + " " + code[1] + " " + code[2] + " " + code[3]);
            desactiverBoutons();
            texte_score.setForeground(Color.GREEN); 
            lancerClignotement();
            parties++;
            victoires++;
            majStats();

        }

        // SI PERDU
        else if (jeu.partieTerminee()) {
            int[] code = jeu.getCodeSecret();
            texte_score.setText("Perdu ! Code secret : " 
                + code[0] + " " + code[1] + " " + code[2] + " " + code[3]);
            desactiverBoutons();
            texte_score.setForeground(Color.RED);
            lancerClignotement();
            parties++;
            majStats();
        }

        // SINON (continuer le jeu)
        else {
            texte_score.setText("Tentatives");
        }
        zone_historique.append("Essai " + jeu.getNbTentatives()
        + " : " + propositionToString()
        + " -> Exact:" + res.getNbExact()
        + " Haut:" + res.getNbTropHaut()
        + " Bas:" + res.getNbTropBas()
        + "\n");
        String combinaison = combinaisonActuelle();

        // Vérifier si la combinaison a déjà été testée
        if (combinaisonsTestees.contains(combinaison)) {
            texte_score.setText("Cette combinaison a déjà été testée!");
            return; 
        }
      
        
        combinaisonsTestees.add(combinaison);
        
        bouton_tester.setEnabled(false);
        chiffreModifie = false;
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        jeu.decrementerChiffre(0);
        rafraichirAffichageChiffres();
        chiffreModifie = true;
        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void bouton_aideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_aideActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
        "Règles du jeu :\n"
        + "- Trouver le code secret (4 chiffres).\n"
        + "- Vous avez " + jeu.getNbTentativesMax() + " tentatives.\n"
        + "- Après chaque test : Exact / Trop haut / Trop bas.",
        "Aide",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    }//GEN-LAST:event_bouton_aideActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_aide;
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_stats;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    private javax.swing.JTextArea zone_historique;
    // End of variables declaration//GEN-END:variables
}
